spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/samps_fmc_flight?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: password

#  datasource:
#    url: jdbc:mysql://localhost:3306/monitor?serverTimezone=UTC
#    username: root
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver

