spring:
  datasource:
    url: jdbc:h2:mem:h2-test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  jpa:
    hibernate:
      ddl-auto: create
#  cloud:
#    stream:
#      rocketmq:
#        binder:
#          name-server: 172.30.3.51:9876;172.30.3.52:9876;172.30.3.53:9876
#      bindings:
#        output:
#          destination: FMC
#        input:
#          destination: FMC
#          group: group03

# 名字服务器地址
rocketmq:
  name-server: 172.30.3.51:9876;172.30.3.52:9876;172.30.3.53:9876

