spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 172.30.3.51:9876;172.30.3.52:9876;172.30.3.53:9876
      bindings:
        output:
          destination: FMC
        input:
          destination: FMC
          group: group03



