spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/samps_fmc_flight?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: password

